AWSTemplateFormatVersion: 2010-09-09
Description:  lecture10-S3
Resources: 
  SampleS3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private 
      BucketName: lecture10-s3bucket
      VersioningConfiguration:
          Status: Enabled
      PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
      BucketEncryption:
          ServerSideEncryptionConfiguration: 
            - ServerSideEncryptionByDefault: 
                SSEAlgorithm: AES256
      Tags:
        - Key: Name
          Value: SampleS3Bucket
  SampleBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SampleS3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
             - s3:GetObject
             - s3:PutObject
             - s3:ListBucket
             - s3:DeleteObject
             - s3:GetBucketLocation  
            Effect: Allow
            Resource: 
             - !Sub arn:aws:s3:::${SampleS3Bucket}
             - !Sub arn:aws:s3:::${SampleS3Bucket}/*       
            Principal: 
              Service: ec2.amazonaws.com
  SampleIamRole:
    Type: AWS::IAM::Role
    Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement: 
            - 
              Effect: "Allow"
              Principal: 
                Service: 
                  - "ec2.amazonaws.com"
              Action: 
                - "sts:AssumeRole"
        Path: "/"
  SampleInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - !Ref SampleIamRole
Outputs:
  SampleInstanceProfile:
      Value: !Ref  SampleInstanceProfile
      Export: 
        Name: SampleInstanceProfile

 